### ISSUE TITLE
d3plus with IE11

### ISSUE THREAD

**Issue by nalhadad** [d3plus/d3plus-website#5]
Hello,
I made few examples in d3plus2 concerning the components TreeMap, Pie and Plot,
They work perfectly with chrome but in IE 11, they don't work (apparently, beacause of the method 'includes' that is used in d3plus. The message error in IE is : Object doesn't support property or method 'includes  ).
Do you have plans to make d3plus2 compatible with IE?
Thank you

**Comment by davelandry** [comment]
@nalhadad we have fixed this `includes` issue in the past, but this may have just been because we haven't rebundled the entire library since then. Can you share your code?

This new bundle should contain the fix: https://d3plus.org/js/d3plus.v2.0.0-alpha.23.full.min.js

**Comment by nalhadad** [comment]
Hello,
Here is one of the examples that didn't work with IE11. I tried it with the version u sent me and it works perfectly. Thank you very much.

<script src="https://d3plus.org/js/d3plus.v2.0.0-alpha.22.full.min.js"></script>
<script src="http://www.d3plus.org/js/d3.min.js"></script>
<div id="viz"></div>
<script>
var sample_data=[{"LivraisonPays":"Argentina" , "year":2015 , "Prix":3 },
{"LivraisonPays":"Argentina" , "year":2022 , "Prix":81 },
{"LivraisonPays":"Argentina" , "year":2014 , "Prix":81 },
{"LivraisonPays":"Argentina" , "year":2022 , "Prix":264 },
{"LivraisonPays":"France" , "year":2022 , "Prix":27 },
{"LivraisonPays":"France" , "year":2012 , "Prix":27 },
{"LivraisonPays":"France" , "year":2016 , "Prix":28 },
{"LivraisonPays":"France" , "year":2017 , "Prix":28 },
{"LivraisonPays":"France" , "year":2012 , "Prix":28 },
{"LivraisonPays":"Austria" , "year":2013 , "Prix":14 },
{"LivraisonPays":"Austria" , "year":2015 , "Prix":15 },
{"LivraisonPays":"Austria" , "year":2015 , "Prix":34 },
{"LivraisonPays":"Austria" , "year":2021 , "Prix":35 },
{"LivraisonPays":"Austria" , "year":2022 , "Prix":36 }
];
var visualization = new d3plus.Treemap()
.select("#viz") 
.data(sample_data) 
.groupBy(["LivraisonPays","year"])  
.sum("Prix")
.depth(1)
.render();
</script>

**Comment by nalhadad** [comment]
Thank you for ur fast replies.
I've already seen this example. This is not exactly what I need. I do not need to relate the colors to the data. I want to define a set of colors and my Treemap/pie assignes these colors to it.
In V1, I could do that, like this example : (http://jsfiddle.net/b754suyw/)
As u can see, I just have to define an array of colors and put it in .color({scale: [my array of colors]})
and My Treemap take this array automaticly.
How to make the same in V2?
Thank you.
